site_name: Project LUX Documentation
site_url: https://project-lux.github.io/documentation/

theme:
  name: material

nav:
  - Home: index.md
  - Human Made Object: hmo.md
  - Digital Object: digitalobject.md
  - Visual Work: visualwork.md
  - Group: group.md
  - Person: person.md

# Optional: Make URLs cleaner
use_directory_urls: true

# Markdown features
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list

extra_css:
  - stylesheets/custom.css

